version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: medgrab_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - medgrab_network

  notification_service:
    build:
      context: .
      dockerfile: atomic/notification/notification.Dockerfile
    container_name: medgrab_notification_service
    env_file:
      - config/.env
    environment:
      - AMQP_HOST=medgrab_rabbitmq
      - AMQP_PORT=5672
      - AMQP_EXCHANGE=medgrab_exchange
      - AMQP_EXCHANGE_TYPE=topic
      - NOTIFICATION_ROUTING_KEY=notification.email
      - NOTIFICATION_QUEUE=email_notifications
    ports:
      - "5002:5002"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - medgrab_network

volumes:
  rabbitmq_data:

networks:
  medgrab_network:
    driver: bridge